-- 1. Registrations table with XentriPAY payment tracking
CREATE TABLE IF NOT EXISTS registrations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  full_name text NOT NULL,
  email text NOT NULL,
  phone text NOT NULL,
  organization text NOT NULL,
  country text NOT NULL,
  role text NOT NULL,
  reason text NOT NULL,
  created_at timestamptz DEFAULT now(),
  payment_ref text,
  payment_status text DEFAULT 'pending'
);

-- 2. Newsletters table
CREATE TABLE IF NOT EXISTS newsletters (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text,
  subtitle text,
  content text,
  status text DEFAULT 'draft',
  created_at timestamptz DEFAULT now()
);

-- 3. Administrator users table
CREATE TABLE IF NOT EXISTS admin_users (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  email text UNIQUE NOT NULL,
  created_at timestamptz DEFAULT now()
);

-- 3b. Insert admin email (Replace with your actual email address)
INSERT INTO admin_users (email)
VALUES ('atanganaayissinestor123@gmail.com')
ON CONFLICT (email) DO NOTHING;

-- 4. Enable Row Level Security (RLS)
ALTER TABLE registrations ENABLE ROW LEVEL SECURITY;
ALTER TABLE newsletters ENABLE ROW LEVEL SECURITY;
ALTER TABLE admin_users ENABLE ROW LEVEL SECURITY;

-- 5. Access Policies (Cleaned up and recreated to prevent conflicts)
DROP POLICY IF EXISTS "Anyone can register" ON registrations;
CREATE POLICY "Anyone can register" ON registrations FOR INSERT TO anon WITH CHECK (true);

DROP POLICY IF EXISTS "Admins can view all registrations" ON registrations;
CREATE POLICY "Admins can view all registrations" ON registrations FOR SELECT TO authenticated USING (
  EXISTS (SELECT 1 FROM admin_users WHERE admin_users.email = (SELECT email FROM auth.users WHERE auth.users.id = auth.uid()))
);

DROP POLICY IF EXISTS "Admins can manage newsletters" ON newsletters;
CREATE POLICY "Admins can manage newsletters" ON newsletters FOR ALL TO authenticated USING (true);